In [68]:
import numpy as np

In [69]:
# 입력
x = np.array([[0,0],[0,1],[1,0],[1,1]])
print(x.shape)
# (4,2): feature(특징)이 2개인 4개의 sample

(4, 2)


In [70]:
# perceptron 정의

def perceptron(x,w,b):
    # 입력 x,w는 ndarray
    # w1x1+w2x2는 w 벡터와 x벡터의 내적
    y = x.dot(w)+b > 0
    return y.astype('int')
    # 반환하는 값이 bool type이므로 astype()로 타입 변경

In [71]:
w = np.array([3,2])
perceptron(x,w,3)

array([1, 1, 1, 1])

In [72]:
# AND
def AND(x_and):
    w_and = np.array([3,4])
    b_and = -5
    return perceptron(x_and,w_and,b_and)

In [73]:
# NAND
def NAND(x_nand):
    w_nand = np.array([-3,-4])
    b_nand = 5
    return perceptron(x_nand,w_nand,b_nand)

In [74]:
# OR
def OR(x_or):
    w_or = np.array([0.5,0.5])
    b_or = -0.3
    return perceptron(x_or,w_or,b_or)

In [75]:
AND(x)

array([0, 0, 0, 1])

In [76]:
NAND(x)

array([1, 1, 1, 0])

In [77]:
OR(x)

array([0, 1, 1, 1])

In [78]:
s1 = NAND(x).reshape(-1,1)
s2 = OR(x).reshape(-1,1)
# NAND와 OR의 결과는 1D
# 때문에 reshape로 2D array로 바꿔줌
# 다음 열을 결합함
np.concatenate((s1,s2),axis=1)

array([[1, 0],
       [1, 1],
       [1, 1],
       [0, 1]])

In [79]:
# XOR (multi-layer perceptron)
def XOR(x_xor):
    s1 = NAND(x_xor).reshape(-1,1) # 입력 값이 2차원이어야 함
    s2 = OR(x_xor).reshape(-1,1)
    y = AND(np.concatenate((s1,s2),axis=1)) # s1과 s2를 열을 기준으로 합침
    return y

In [80]:
XOR(x)

array([0, 1, 1, 0])