In [3]:
import numpy as np

a = 2
x = np.array([1,2,3])

print(a * x)

[2 4 6]


In [5]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x+y)

[5 7 9]


In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([4,5,6])

print(x+y)

In [8]:
x = [1, 2, 3, 4, 5]
y = [3, 4, 5]
print(x+y)

[1, 2, 3, 4, 5, 3, 4, 5]


In [10]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x-y)

[-3 -3 -3]


In [11]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x*y)

[ 4 10 18]
