In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('C:\data\sample.csv').values
print(type(dataset))
dataset

<class 'numpy.ndarray'>


array([['James', 'France', 44.0, 72000.0, 'No'],
       ['Tim', 'Spain', 27.0, 48000.0, 'Yes'],
       ['Sarah', 'Germany', 30.0, 54000.0, 'No'],
       ['Robert', 'Spain', 38.0, 61000.0, 'No'],
       ['Emma', 'Germany', 40.0, nan, 'Yes'],
       ['Jennifer', 'France', 35.0, 58000.0, 'Yes'],
       ['Linda', 'Spain', nan, 52000.0, 'No'],
       ['Thomas', 'France', 48.0, 79000.0, 'Yes'],
       ['Ben', 'Germany', 50.0, 83000.0, 'No'],
       ['Scarlett', 'France', 37.0, 67000.0, 'Yes']], dtype=object)

In [4]:
# x는 전체 행, 국적(1),나이(2),연봉(3)
x = dataset[:,1:-1]
print(x)

# y = 전체 행, 마지막 열
y = dataset[:,-1]
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
print(x.shape)
print(y.shape)

(10, 3)
(10,)


In [6]:
from sklearn.preprocessing import LabelEncoder
# 문자를 0부터 n까지의 정수로 변환
le = LabelEncoder()
# X의 첫번째열에 LabelEncoder 적용
le.fit(x[:,0])
# fit은 실제 변형되지 않고, 정보 수집 및 변환 전략 수립
# 어떻게 변형할지 정보 수집
x_c = le.transform(x[:,0])
# tranform은 fit에서 결정된 정보 기반으로 실제 변환 수행 후 결과 반환
# 데이터 스케일링
x_c

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [7]:
x_tmp = np.delete(x,0,axis=1)
x_new = np.concatenate((x_c.reshape(-1,1),x_tmp),axis=1)
x_new

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [16]:
# OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
# OneHotEncoder는 반드시 2차원이어야 함
ohe = OneHotEncoder()
ohe.fit(x[:,0].reshape(-1,1))
x_ohe = ohe.transform(x[:,0].reshape(-1,1)).toarray()
# OneHotEncoder의 tranform 결과는 sparse matrix임
# ndarray로 변경하기 위해 .toarray()사용함
# sparse matrix 사용하는 이유는 메모리 공간 아끼려고
x_ohe

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [9]:
x_new_ohe = np.concatenate((x_ohe,x_tmp),axis=1)
x_new_ohe

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, nan, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 5)
# test_size : 전체 데이터 수에 대한 test data의 비율

# model 성능 비교 위해선 동일한 dataset사용해야 함 = random_state
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(8, 3) (2, 3)
(8,) (2,)


In [11]:
# scaler: 데이터의 범위 조정
x = dataset[:,2:-1]
y = dataset[:,-1]
print(x.shape,y.shape)

(10, 2) (10,)


In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# 평균은 0, 분산(표준편차)은 1로 변경한 데이터 ( 주로 -3~3 의 값)
# 0을 중심으로 위 아래 값으로 구함
# 실제로 데이터가 분포되어 있는 특성을 가져옴
sc.fit(x_train)
# 변환을 위한 전략 수립(데이터의 평균, 분산 계산)
x_train_sc = sc.transform(x_train)
# 0에 가까울 수록 평균에 가까운 값

# test 값의 변환은 fit 적용하지 않고 x_train으로 수립한 전략으로
# 변환만 수행한다.
x_test_sc = sc.transform(x_test)

In [19]:
x_test_sc

array([[-0.04242853,         nan],
       [-1.97292657, -1.65205652]])