In [1]:
import numpy as np

In [2]:
# MLP model
# input layer node: 2개
# hidden layer node: 4개
# output layer node: 3개

In [3]:
# input X 및 w(가중치), b(편향)
# sample의 수와 관계없이 실행
# x는 반드시 2D array여야 하며,x.shape[1]은 2여야 함

In [8]:
# X가 5개의 sample일 경우 x.shape = (5,2)
x = np.array([[0,1],
    [1,1],
    [-1,0],
    [2,-1],
    [-1,1]])

#-------------input layer -> hidden layer-----------------

# W1.shape = (2,4) (input layer(출발), 첫번째 hidden layer node(도착))
w1 = np.array([[0.5,0.2,-0.3,0.1],
     [-0.2,0.7,-0.4,0.8]])

# b1.shape(4,) (hidden layer node(도착))
b1 = np.array([0.3,-0.1,0.5,-0.4])

#-------------hidden layer -> output layer----------------
    
# w2.shape(4,3) (hidden layer node(출발), output layer node(도착))
w2 = np.array([[0.2,0.7,-0.3],
              [0.8,-0.5,-0.1],
              [0.1,0.5,0.3],
              [-0.6,0.4,0.7],])

# b2.shape(3,) (output layer node(도착))
b2 = np.array([-0.5,0.9,-0.2])

In [14]:
# activation function (sigmoid)

In [22]:
def sigmoid(a):
    return 1/(1+np.exp(-a))
# 입력 a와 동일한 shape의 ndarray를 반환함
# 위 식이 입력 a의 각 원소에 적용됨

In [23]:
sigmoid(x)

array([[0.5       , 0.73105858],
       [0.73105858, 0.73105858],
       [0.26894142, 0.5       ],
       [0.88079708, 0.26894142],
       [0.26894142, 0.73105858]])

In [26]:
# input layer -> hidden layer(a1, z1)
# a1과 z1의 shape = (5,4) (sample의 수, hidden layer node의 수)
# x.dot(w1): x.shape[1]과 w1.shape[0]은 반드시 동일해야 함
print(x.shape, w1.shape)
a1 = x.dot(w1) + b1
print(a1.shape)
# a1의 각 행은 x의 각 행에 대한 hidden layer node에 대응되는 값
# 그러므로, x의 행과 a1의 행은 동일해야 함

(5, 2) (2, 4)
(5, 4)


In [27]:
# z1은 a1이 activation function(sigmoid)를 통과한 결과
z1 = sigmoid(a1)
# z1은 a1과 동일한 shape
print(z1.shape)

(5, 4)


In [29]:
# hidden layer -> output layer
# 입력 z1
# z1.shape = (5,4) (sample의 수, hidden layer node의 수)
# w2.shape = (4,3) (hidden layer node 수, output layer node의 수)
# b2.shape = (3,) (output layer node의 수)
a2 = z1.dot(w2)+b2
# a2의 각 행은 입력값 z1의 각 행에 대한 output layer node에 대응되는 값 
print(a2.shape)

(5, 3)


In [32]:
y = sigmoid(a2)
print(y.shape)
# y의 각 행은 입력 X의 각 행에 대한 output layer node의 최종 값
# 그러므로, y.shape = (sample의 수, output layer node의 수)
print(y)
# y는 a2에 대한 sigmoid 값이므로 0~1 사이의 값을 가짐
# -> 가장 큰 값을 갖는 node에 해당하는 class로 판단

(5, 3)
[[0.45383342 0.809478   0.53855226]
 [0.46322947 0.81472945 0.52699298]
 [0.44348065 0.81732691 0.52339921]
 [0.47019641 0.84110111 0.46883749]
 [0.44384191 0.80387564 0.55019376]]


# Softmax

In [43]:
def softmax(a):
    return np.exp(a) / np.exp(a).sum(axis=1).reshape(-1,1)

In [45]:
a2 = z1.dot(w2)+b2
y = softmax(a2)
print(y.shape)
print(y)
# 최종 class index 반환
# np.argmax(ndarray)는 최대값을 갖는 index를 반환
# 각 행의 최대값 index를 추출하기 위해 axis=1 지정
np.argmax(y,axis=1)

(5, 3)
[[0.13301959 0.68014915 0.18683127]
 [0.13537919 0.68984486 0.17477594]
 [0.12511239 0.70246896 0.17241865]
 [0.12564541 0.74939284 0.12496175]
 [0.13039956 0.66973566 0.19986478]]


array([1, 1, 1, 1, 1], dtype=int64)